import swaggerJsDoc from "swagger-jsdoc";

const options = {
    apis: ["./dist/Features/users/user.router.js"],
    swaggerDefinition: {
        basepath: "/",
        info: {
            description: process.env.APP_NAME,
            title: process.env.APP_TITLE,
            version: process.env.APP_VERSION,
        },
        schemes: {
            name: "http",
        },
        securityDefinitions: {
            Bearer: {
                description: "For accessing the API a valid JWT token must be passed in all the queries in the Authorization header A valid JWT token is generated by the API and retourned as answer of a call to the route /login giving a valid user & password. The following syntax must be used in the Authorization header : \n Bearer: xxxxxx.yyyyyyy.zzzzzz",
                in: "header",
                name: "authorization",
                type: "apiKey",
            }
        },
    },
};

export default swaggerJsDoc(options);